services:
  - type: worker
    name: takers-slave-userbot
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    autoDeploy: true
    envVars:
      API_ID: "24332704"
      API_HASH: "8fb6431a21aed74c770c79c8eb4b9616"
      ADMIN_ID: "8480948917"
      SESSION: "spam_session"
